# Generated by Django 4.2.1 on 2023-05-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.IntegerField(choices=[(0, 'Друзья'), (1, 'Входящая заявка'), (-1, 'Исходящая заявка')]),
        ),
    ]
